name: CI

on:
  pull_request:
    branches: [ '*' ]
  merge_group:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - uses: astral-sh/setup-uv@v6
      - name: 安装依赖
        run: uv sync --locked --dev
      - name: 运行 Ruff 格式检查
        run: uv run ruff format --check .
      - name: 运行 Ruff Lint
        run: uv run ruff check .
      - name: 运行类型检查
        run: uv run basedpyright src/quack

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - uses: astral-sh/setup-uv@v6
      - name: 安装依赖
        run: uv sync --locked --dev
      - name: 运行测试
        run: uv run pytest .
